- name: Deploy the Headscale stack
  hosts: '{{ target_group | default("polaris_hosts") }}'
  tags:
    - polaris.overlay
    - polaris.overlay.headscale
  roles:
    - role: stackmanager
      vars:
        tagged: headscale
