- name: Deploy the Headscale stack
  hosts: polaris_hosts
  tags:
    - polaris.layer.overlay
    - polaris.layer.overlay.headscale
  roles:
    - role: stackmanager
      vars:
        tagged: headscale
