- name: Setup Tailscale
  hosts: '{{ target_group | default("polaris_hosts") }}'
  tags:
    - polaris.overlay
    - polaris.overlay.tailscale_client
  tasks:
    - name: Setup tailscale client
      include_role:
        name: artis3n.tailscale
      vars:
        tailscale_args: '{{ polaris_tailscale_args | default(omit) }}'
        tailscale_authkey: '{{ polaris_tailscale_authkey | default(omit) }}'
        tailscale_up_skip: '{{ false if (polaris_tailscale_authkey is defined) else true }}'
