- name: Setup Tailscale
  hosts: polaris_hosts
  tags:
    - polaris.overlay
    - polaris.overlay.tailscale_client
  tasks:
    - name: Setup tailscale client
      include_role:
        name: artis3n.tailscale
      vars:
        tailscale_args: "{{ polaris_tailscale_args|default('') }}"
        tailscale_authkey: "{{ polaris_tailscale_authkey }}"
