# See https://docs.ansible.com/ansible/latest/dev_guide/collections_galaxy_meta.html

namespace: linkorb
name: polaris
version: 0.1.0
readme: README.md
authors:
  - LinkORB (github.com/linkorb)
description: Webapp Infrastructure
license_file: LICENSE
tags:
  - juicefs
  - tailscale
  - prometheus
  - docker
  - swarm
repository: https://github.com/linkorb/ansible-collection-polaris
#documentation: https://github.com/ansible-collection-migration/community.REPO_NAME/tree/main/docs
homepage: https://github.com/linkorb/ansible-collection-polaris
issues: https://github.com/linkorb/ansible-collection-polaris/issues
build_ignore:
# https://docs.ansible.com/ansible/devel/dev_guide/developing_collections_distributing.html#ignoring-files-and-folders
  - .gitignore
  - changelogs/.plugin-cache.yaml

dependencies:
  community.docker: '>=1.0.0'
  community.sops: '>=1.0.0'
  ansible.posix: '>=1.0.0'
  devsec.hardening: '>=1.0.0'
