# This file defines the Shipyard stack *default* values, which can be overridden through a stack-specific values file

image:
  repository: traefik
  tag: latest

# required values are initialized with null, not with (invalid) example values.
hostname: loadbalancer
