# These tasks are included once per stack

- name: 'The stack directory for {{ stack.name }} is present on the managed node'
  become: true
  ansible.builtin.file:
    path: '{{ stack.remote_path }}'
    state: directory
    mode: '0700'

- name: Deploy the stack's directories
  become: true
  when: item.state == 'directory'
  block:
  - name: 'Print directories that will be present in the {{ stack.name }} stack directory'
    with_community.general.filetree: '{{ stack.local_path }}/'
    ansible.builtin.debug:
      msg: 'directory: {{ stack.remote_path }}/{{ item.path }}; mode: {{ item.mode }}'
      verbosity: 1
  - name: 'Directories are present in the {{ stack.name }} stack directory'
    with_community.general.filetree: '{{ stack.local_path }}/'
    ansible.builtin.file:
      path: '{{ stack.remote_path }}/{{ item.path }}'
      state: directory
      mode: '{{ item.mode }}'

- name: Deploy the stack's static files
  become: true
  when:
    - item.state == 'file'
    - item.path | splitext | last not in ['.j2', '.j2mt']
  block:
  - name: 'Print static files that will be present in the {{ stack.name }} stack directory'
    with_community.general.filetree: '{{ stack.local_path }}/'
    ansible.builtin.debug:
      msg: 'file: {{ stack.remote_path }}/{{ item.path }}; mode: {{ item.mode }}'
      verbosity: 1
  - name: 'Static files are present in the {{ stack.name }} stack directory'
    with_community.general.filetree: '{{ stack.local_path }}/'
    become: true
    ansible.builtin.copy:
      src: '{{ stack.local_path }}/{{ item.path }}'
      dest: '{{ stack.remote_path }}/{{ item.path }}'
      mode: u=rw,g=r,o=r

- name: Deploy the stack's multi-tenant templates (each template results in a file per tenant)
  with_community.general.filetree: '{{ stack.local_path }}/'
  when:
    - mt_filespec.state == 'file'
    - mt_filespec.path | splitext | last == '.j2mt'
  include_tasks: templated-file-per-tenant.yml
  loop_control:
    loop_var: mt_filespec

- name: Deploy the stack's templated files
  become: true
  when:
    - item.state == 'file'
    - item.path | splitext | last == '.j2'
  block:
  - name: 'Print templated files that will be present in the {{ stack.name }} stack directory'
    with_community.general.filetree: '{{ stack.local_path }}/'
    become: true
    ansible.builtin.debug:
      msg: 'file: {{ stack.remote_path }}/{{ item.path | splitext | first }}; mode: {{ item.mode }}'
      verbosity: 1
  - name: 'Templated files are present in the {{ stack.name }} stack directory'
    with_community.general.filetree: '{{ stack.local_path }}/'
    ansible.builtin.template:
      src: '{{ stack.local_path }}/{{ item.path }}'
      dest: '{{ stack.remote_path }}/{{ item.path | splitext | first }}'
      mode: u=rw,g=r,o=r

- name: 'Docker volumes for {{ stack.name }} config are pesent in the swarm'
  become: true
  community.docker.docker_volume:
    name: '{{ item.name }}'
    state: present
  loop: '{{ stack.config_volumes | default([]) }}'

- name: 'Docker volumes for {{ stack.name }} config are populated with their data'
  become: true
  ansible.builtin.shell:
    cmd: 'tar --directory={{ stack.remote_path }}/{{ item.path }} --create --file=- . | docker run --rm --interactive --volume {{ item.name }}:/data alpine tar --directory=/data --extract --verbose --file=- && touch {{ stack.remote_path }}/{{ item.path }}/.done'
    creates: '{{ stack.remote_path }}/{{ item.path }}/.done'
  loop: '{{ stack.config_volumes | default([]) }}'

- name: 'Docker secrets are present'
  become: true
  community.docker.docker_secret:
    name: '{{ item.name }}'
    data: '{{ item.data | b64encode }}'
    data_is_b64: true
    state: present
  loop: '{{ docker_secrets | default([]) }}'

- name: 'Deploy stack'
  become: true
  docker_stack:
    name: '{{ stack.name }}'
    state: present
    with_registry_auth: true
    prune: true
    compose:
         - '{{ stack.remote_path }}/docker-compose.yml'
