---
- name: 'Establish facts about local and remote stack paths'
  set_fact:
    path_to_manifest: '{{ path_to_stacks_manifest | default(inventory_dir ~ "/stacks/manifest.yaml") }}'
    local_path_to_stacks: '{{ path_to_stacks_on_control_node | default(inventory_dir ~ "/stacks/") }}'
    remote_path_to_stacks: '{{ path_to_stacks_on_managed_node | default("/opt/stacks/") }}'

- name: 'Read the stack manifest'
  set_fact:
    manifest: '{{ (lookup("template", path_to_manifest, errors="ignore") | from_yaml).stacks | default(stacks) | default([]) }}'

- name: 'Initialize a list of selected stacks to deploy'
  set_fact:
    selected_stacks: []
    stacks_to_deploy: []

- name: 'Select stacks to deploy on this host'
  set_fact:
    selected_stacks: '{{ selected_stacks + [item] }}'
  loop: '{{ manifest }}'
  when:
  - item.host == inventory_hostname
  - tagged is not defined or (item.tag is defined and tagged == item.tag)

- name: 'Enrich selected stacks with path info'
  set_fact:
    stacks_to_deploy: '{{ stacks_to_deploy + [item | combine({"local_path": local_path_to_stacks~(item.path|default(item.name)), "remote_path": remote_path_to_stacks~item.name})] }}'
  loop: '{{ selected_stacks }}'

- name: 'Debug: manifest'
  ansible.builtin.debug:
    var: manifest
    verbosity: 1
  when: stacks_to_deploy | length

- name: 'Debug: stacks_to_deploy (selected and enriched)'
  ansible.builtin.debug:
    var: stacks_to_deploy
  when: stacks_to_deploy | length

- name: 'Deploy stacks'
  include_tasks: deploy-stack.yml
  loop: '{{ stacks_to_deploy }}'
  loop_control:
    label: 'Deploy stack: [{{ stack.name }}]'
    loop_var: stack
