- name: Logging - containers
  hosts: polaris_hosts
  tags:
    - polaris.logging
    - polaris.logging.containers
  tasks:
    - name: Setup Loki and Promtail containers
      import_role:
        name: stackmanager
      vars:
        tagged: logging
