- name: Deploy app stacks
  hosts: polaris_hosts
  tags:
    - polaris.app
    - polaris.app.stacks
  roles:
    - role: stackmanager
      vars:
        tagged: app
        docker_secrets: '{{ polaris_docker_secrets_for_stacks }}'
