- name: Shipyard - app stacks
  hosts: polaris_hosts
  tags:
    - polaris.layer.app
    - polaris.layer.app.stacks
  roles:
    - role: linkorb.shipyard
      vars:
        shipyard_tag: app
        shipyard_stacks_docker_secrets: '{{ polaris.docker_secrets_for_shipyard_stacks }}'
