- name: Baseline - admins
  hosts: '{{ target_group | default("polaris_hosts") }}'
  become: yes
  tags:
    - polaris.baseline
    - polaris.baseline.admins
  roles:
    - role: cchurch.admin-users
      admin_users: "{{ polaris_admins_active }}"
      admin_users_to_remove: "{{ polaris_admins_removed }}"
