- name: Baseline - configuration
  hosts: polaris_hosts
  become: true
  tags:
    - polaris.layer.baseline
    - polaris.layer.baseline.config
  roles:
    - name: "Pip Packages"
      role: geerlingguy.pip
      vars:
        pip_install_packages:
          - name: docker  # docker python sdk (required by docker / swarm module)
            version: ">6.0.1,<7.0.0"
          - name: jsondiff
    - name: "IPv6 is disabled"
      role: ypsman.ipv6_disable
    - name: "Time is Synchronised"
      role: linux-system-roles.timesync
      vars:
        timesync_ntp_servers:
          - hostname: 0.ubuntu.pool.ntp.org
            pool: true
            iburst: true
          - hostname: 1.ubuntu.pool.ntp.org
            pool: true
            iburst: true
          - hostname: 2.ubuntu.pool.ntp.org
            pool: true
            iburst: true
          - hostname: 3.ubuntu.pool.ntp.org
            pool: true
            iburst: true
