- name: Hosts are configured in the standard manner
  hosts: polaris_hosts
  become: true
  tags:
  - polaris.layer.baseline
  - polaris.layer.baseline.config
  tasks:

  - name: The host name is correct
    ansible.builtin.hostname:
      name: '{{ inventory_hostname }}'

  - name: The host name is present in /etc/hosts
    ansible.builtin.lineinfile:
      dest: /etc/hosts
      regexp: '^127\.0\.0\.1[ \t]+localhost'
      line: '127.0.0.1 localhost {{ inventory_hostname }}'
      state: present

  - name: Python packages needed by Ansible are installed by Pip
    ansible.builtin.import_role:
      name: geerlingguy.pip
    vars:
      pip_install_packages:
      - name: jsondiff

  - name: IPv6 is disabled
    ansible.builtin.import_role:
      name: ypsman.ipv6_disable

  - name: Time is Synchronised
    ansible.builtin.import_role:
      name: linux-system-roles.timesync
    vars:
      timesync_ntp_servers:
      - hostname: 0.ubuntu.pool.ntp.org
        pool: true
        iburst: true
      - hostname: 1.ubuntu.pool.ntp.org
        pool: true
        iburst: true
      - hostname: 2.ubuntu.pool.ntp.org
        pool: true
        iburst: true
      - hostname: 3.ubuntu.pool.ntp.org
        pool: true
        iburst: true
