- name: Baseline - packages
  hosts: polaris_hosts
  become: true
  tags:
    - polaris.baseline
    - polaris.baseline.packages
  tasks:
    - name: install default apt packages
      ansible.builtin.apt:
        name:
          - auditd
          - audispd-plugins
          - apt-transport-https
          - ca-certificates
          - curl
          - fail2ban
          - fuse
          - git
          - gnupg
          - htop
          - jq
          - lsb-release
          - net-tools
          - ngrep
          - nmap
          - screen
          - software-properties-common
          - sudo
          - tmux
          - tree
          - unzip
          - vim
          - vnstat
          - zip
        state: present
