- name: Baseline - packages
  hosts: polaris_hosts
  become: true
  tags:
    - polaris.layer.baseline
    - polaris.layer.baseline.packages
  tasks:
    - name: install default apt packages
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - fuse
          - gnupg
          - lsb-release
          - software-properties-common
          - vim
          - nmap
          - ngrep
        state: present

