- name: Host is running a Prometheus Node Exporter
  hosts: polaris_hosts
  become: true
  tags:
    - polaris.layer.baseline
    - polaris.layer.baseline.prometheus_node_exporter
  tasks:
    - name: Prometheus Node Exporter is installed
      ansible.builtin.import_role:
        name: prometheus.prometheus.node_exporter
