- name: Docker engine installation
  hosts: polaris_hosts
  become: true
  tags:
    - polaris.layer.container
    - polaris.layer.container.docker_engine
  roles:
    - geerlingguy.docker

- name: Docker config
  hosts: polaris_hosts
  tags:
    - polaris.layer.container
    - polaris.layer.container.docker_engine
  tasks:
    - name: Adding docker users (for use without sudo)
      user:
        name: "{{ item }}"
        append: true
        groups: docker
      become: true
      with_items: '{{ polaris.docker_users }}'
    - name: Install and enable juicedata/juicefs volume plugin
      community.docker.docker_plugin:
        plugin_name: "juicedata/juicefs:1.1.1"
        state: enable
        alias: juicefs
      become: true

- name: Docker registry login
  hosts: polaris_hosts
  tags:
    - polaris.layer.container
    - polaris.layer.container.docker_engine
    - polaris.layer.container.docker_engine.registry_login
  tasks:
    - name: Login to the Docker Container Registry
      community.general.docker_login:
        registry: "{{ polaris.docker_registry|default('https://ghcr.io/') }}"
        username: "{{ polaris.docker_registry_username }}"
        password: "{{ polaris.docker_registry_pat }}"
      become: true
        # reauthorize: true
