- name: Docker Swarms are initialised on Primary Swarm Managers
  hosts: "{{ polaris_primary_swarm_managers | default('polaris_primary_swarm_managers') }}"
  become: true
  tags:
    - polaris.container
    - polaris.container.swarm
  tasks:
  - name: Host has dependencies of ansible modules
    ansible.builtin.include_tasks: tasks/install_module_dependencies.yaml
  - name: Initialise a Swarm on this Host
    community.docker.docker_swarm:
      state: present
      advertise_addr: "{{ polaris.docker_swarm_advertise_address | default(omit) }}"
      listen_addr: "{{ polaris.docker_swarm_advertise_address | default(omit) }}"
    register: swarm_initialisation_info
  - name: Peek at swarm_initialisation_info
    debug:
      var: swarm_initialisation_info
      verbosity: 3
  - name: Remember swarm_initialisation_info for use by other hosts
    ansible.builtin.set_fact:
      swarm_initialisation_info: "{{ swarm_initialisation_info }}"
      cacheable: yes


- name: Secondary Swarm Managers are joined to their Swarms
  hosts: "{{ polaris_secondary_swarm_managers | default('polaris_secondary_swarm_managers') }}"
  become: true
  tags:
    - polaris.container
    - polaris.container.swarm
  tasks:
  - name: Host has dependencies of ansible modules
    ansible.builtin.include_tasks: tasks/install_module_dependencies.yaml
  - name: Grab a Swarm Manager JoinToken
    ansible.builtin.set_fact:
      target_swarm_facts: "{{ hostvars[join_swarm_initialised_by].ansible_facts }}"
  - name: Peek at target_swarm_facts (facts about a target swarm)
    debug:
      var: target_swarm_facts
      verbosity: 3
  - name: Host is joined to a Swarm as a Manager Node
    community.docker.docker_swarm:
      state: join
      join_token: "{{ target_swarm_facts.swarm_initialisation_info.swarm_facts.JoinTokens.Manager }}"
      advertise_addr: "{{ polaris.docker_swarm_advertise_address | default(omit) }}"
      listen_addr: "{{ private_ip_address | default(omit) }}"
      remote_addrs:
      - "{{ polaris.docker_swarm_advertise_address | default(target_swarm_facts.default_ipv4.address) | default(target_swarm_facts.all_ipv4_addresses[0]) }}"


- name: Swarm Workers are joined to their Swarms
  hosts: "{{ polaris_swarm_nodes | default('polaris_swarm_nodes') }}"
  become: true
  tags:
    - polaris.container
    - polaris.container.swarm
  tasks:
  - name: Host has dependencies of ansible modules
    ansible.builtin.include_tasks: tasks/install_module_dependencies.yaml
  - name: Grab a Swarm Manager JoinToken
    ansible.builtin.set_fact:
      target_swarm_facts: "{{ hostvars[join_swarm_initialised_by].ansible_facts }}"
  - name: Peek at target_swarm_facts (facts about a target swarm)
    debug:
      var: target_swarm_facts
      verbosity: 3
  - name: Host is joined to a Swarm as a Worker Node
    community.docker.docker_swarm:
      state: join
      join_token: "{{ target_swarm_facts.swarm_initialisation_info.swarm_facts.JoinTokens.Worker }}"
      advertise_addr: "{{ polaris.docker_swarm_advertise_address | default(omit) }}"
      listen_addr: "{{ private_ip_address | default(omit) }}"
      remote_addrs:
      - "{{ polaris.docker_swarm_advertise_address | default(target_swarm_facts.default_ipv4.address) | default(target_swarm_facts.all_ipv4_addresses[0]) }}"
