# Configure users
- name: users
  hosts: '{{ target_group | default("polaris_hosts") }}' # use -l to limit your hosts
  gather_facts: false
  become: true
  roles:
    - role: cchurch.admin-users
      admin_users: "{{ polaris_admins_active }}"

- name: python
  hosts: '{{ target_group | default("polaris_hosts") }}' # use -l to limit your hosts
  gather_facts: false
  become: true
  tasks:
    - name: install python
      ansible.builtin.apt:
        name: python3
        state: present
