version: "3.3"

services:

  lb:
    image: {{ Values.image.repository }}:{{ Values.image.tag }}
    command:
      - "--configFile=/etc/traefik/config.yaml"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/traefik:/etc/traefik
      - /var/log/traefik:/var/log/traefik

    ports:
      - "80:80"
      - "443:443"
      #- "8080:8080"

    deploy:
      mode: global
      labels:
        - "orchestrator=shipyard"

      placement:
        constraints:
          - node.role == manager

    networks:
      - traefik

networks:
  traefik:
    external: true
